
GET http://localhost:3030/api/photo-portfolio/getPhotosPortfolio

###


GET http://localhost:3030/api/photo-portfolio/getPhotoPortfolioByTitle/Logo

###

POST http://localhost:3030/api/photo-portfolio/createPhotoPortfolio
Content-Type: application/json

{
  "title": "Diana",
  "description": "Diana",
  "url": "https://res.cloudinary.com/dtem45qog/image/upload/v1715372905/Senza_titolo-diana_hgb3me.jpg"
}

###

GET http://localhost:3030/api/photo-portfolio/getPhotoPortfolio/663b7e58922d3dbabfa2cfcc

###

PATCH http://localhost:3030/api/photo-portfolio/updatePhotoPortfolio/663ce63eba5e45efbe5c9865
Content-Type: application/json

{
  "url": "https://drive.google.com/file/d/1ccxTjEmEHRLk_lOHiapjFShVfuCj6aPt/view?usp=sharing"
}

###

DELETE http://localhost:3030/api/photo-portfolio/deletePhotoPortfolio/663b738e9f1e8131ab19b7c0

###

POST http://localhost:3030/api/photo-portfolio/createPhotoPortfolio
Content-Type: application/json

{
  "title": "foto con commento",
  "description": "foto con commento",
  "url": "https://drive.google.com/fie/d/1Lmx1kbnd5GKVCwvol0ONOCxwF__8e6Et/view?usp=drive_lin/",
  "commentText": "Bellissima foto!",
  "rating": 5
}

###

POST http://localhost:3030/api/photo-portfolio/addComment/663ce63eba5e45efbe5c9865
Content-Type: application/json

{
  "text": "Bello lo scricciolo",
  "rating": 5
}

###

DELETE http://localhost:3030/api/photo-portfolio/deleteComment/663b86c7bb7bf97a4257e545/663b8734bb7bf97a4257e54f
