GET http://localhost:3030/api/photo-download/getPhotosDownload

###

POST http://localhost:3030/api/photo-download/createPhotoDownload
Content-Type: application/json

{
  "title": "foto",
  "description": "foto 35",
  "url": "https://drive.google.com/fil/d/1G418ZtRJKaR5cfYQHPNfmx28UTAHx389/view?usp=drive_link"
}

###

GET http://localhost:3030/api/photo-download/getPhotoDownload/663b7d691e23627fad976556

###

PATCH http://localhost:3030/api/photo-download/updatePhotoDownload/663b7d691e23627fad976556
Content-Type: application/json

{
  "title": "Nuovo Titolo"
}

###

DELETE http://localhost:3030/api/photo-download/deletePhotoDownload/663b7d691e23627fad976556
