GET http://localhost:3030/getPhotosDownload

###

POST http://localhost:3030/createPhotoDownload
Content-Type: application/json

{
  "title": "foto 5",
  "description": "foto 35",
  "url": "https://drive.google.com/fil/d/1G416C8ZtRJKaR5cfYQHPNfmx28UTAHx3/view?usp=drive_link"
}


###

GET http://localhost:3030/getPhotoDownload/663b7d691e23627fad976556

###

PATCH http://localhost:3030/updatePhotoDownload/663b7d691e23627fad976556
Content-Type: application/json

{
  "title": "Nuovo Titolo"
}

###

DELETE http://localhost:3030/deletePhotoDownload/663b7d691e23627fad976556